image: Visual Studio 2022
build_script:
  - cmd: dotnet build --configuration Release
test:
  assemblies:
    only:
      - '**\*.Tests.dll'
test_script:
  - dotnet test --configuration Release --no-build
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
