image: Visual Studio 2022
build_script:
  - cmd: dotnet build --configuration Release
test:
  assemblies:
    only:
      - '**\*.Tests.dll'
environment:
  PAKET_BOOTSTRAPPER_TRACE: true
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
